/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITreasury, ITreasuryInterface } from "../ITreasury";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_profits",
        type: "uint256",
      },
    ],
    name: "acceptPlay",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_winning",
        type: "uint256",
      },
      {
        internalType: "address payable",
        name: "_winner",
        type: "address",
      },
    ],
    name: "distributePlayWinnings",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_winning",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_profits",
        type: "uint256",
      },
      {
        internalType: "address payable",
        name: "_winner",
        type: "address",
      },
    ],
    name: "payGameSessionWinnings",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "receiveRngPayment",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "address payable",
        name: "_sendTo",
        type: "address",
      },
      {
        internalType: "string",
        name: "_assetType",
        type: "string",
      },
    ],
    name: "sendAvax",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_bet",
        type: "uint256",
      },
    ],
    name: "takeGameSessionBet",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class ITreasury__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasuryInterface {
    return new utils.Interface(_abi) as ITreasuryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITreasury {
    return new Contract(address, _abi, signerOrProvider) as ITreasury;
  }
}
