/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface GamebitTreasuryInterface extends utils.Interface {
  contractName: "GamebitTreasury";
  functions: {
    "acceptPlay(uint256,uint256)": FunctionFragment;
    "distributePlayWinnings(uint256,address)": FunctionFragment;
    "getFunds()": FunctionFragment;
    "getGameFunds(address)": FunctionFragment;
    "pay(uint256,address)": FunctionFragment;
    "payGameSessionWinnings(uint256,uint256,address)": FunctionFragment;
    "receiveOraclePayment(address)": FunctionFragment;
    "receiveRngPayment()": FunctionFragment;
    "takeGameSessionBet(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptPlay",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributePlayWinnings",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "getFunds", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getGameFunds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "pay",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "payGameSessionWinnings",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveOraclePayment",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveRngPayment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "takeGameSessionBet",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "acceptPlay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributePlayWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payGameSessionWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveOraclePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveRngPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "takeGameSessionBet",
    data: BytesLike
  ): Result;

  events: {
    "GameBalanceChanged(address,uint256)": EventFragment;
    "GameFundsReceived(address,uint256)": EventFragment;
    "ProfitTaken(uint8,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GameBalanceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GameFundsReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProfitTaken"): EventFragment;
}

export type GameBalanceChangedEvent = TypedEvent<
  [string, BigNumber],
  { _game: string; _amount: BigNumber }
>;

export type GameBalanceChangedEventFilter =
  TypedEventFilter<GameBalanceChangedEvent>;

export type GameFundsReceivedEvent = TypedEvent<
  [string, BigNumber],
  { _game: string; _amount: BigNumber }
>;

export type GameFundsReceivedEventFilter =
  TypedEventFilter<GameFundsReceivedEvent>;

export type ProfitTakenEvent = TypedEvent<
  [number, BigNumber, string],
  { _type: number; _amount: BigNumber; _game: string }
>;

export type ProfitTakenEventFilter = TypedEventFilter<ProfitTakenEvent>;

export interface GamebitTreasury extends BaseContract {
  contractName: "GamebitTreasury";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GamebitTreasuryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptPlay(
      _amount: BigNumberish,
      _profits: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    distributePlayWinnings(
      _winning: BigNumberish,
      _winner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getFunds(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGameFunds(
      _game: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pay(
      _amount: BigNumberish,
      _sendTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    payGameSessionWinnings(
      _winning: BigNumberish,
      _profits: BigNumberish,
      _winner: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    receiveOraclePayment(
      _game: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    receiveRngPayment(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    takeGameSessionBet(
      _bet: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptPlay(
    _amount: BigNumberish,
    _profits: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  distributePlayWinnings(
    _winning: BigNumberish,
    _winner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getFunds(overrides?: CallOverrides): Promise<BigNumber>;

  getGameFunds(_game: string, overrides?: CallOverrides): Promise<BigNumber>;

  pay(
    _amount: BigNumberish,
    _sendTo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  payGameSessionWinnings(
    _winning: BigNumberish,
    _profits: BigNumberish,
    _winner: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  receiveOraclePayment(
    _game: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  receiveRngPayment(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  takeGameSessionBet(
    _bet: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptPlay(
      _amount: BigNumberish,
      _profits: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    distributePlayWinnings(
      _winning: BigNumberish,
      _winner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getFunds(overrides?: CallOverrides): Promise<BigNumber>;

    getGameFunds(_game: string, overrides?: CallOverrides): Promise<BigNumber>;

    pay(
      _amount: BigNumberish,
      _sendTo: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    payGameSessionWinnings(
      _winning: BigNumberish,
      _profits: BigNumberish,
      _winner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    receiveOraclePayment(
      _game: string,
      overrides?: CallOverrides
    ): Promise<void>;

    receiveRngPayment(overrides?: CallOverrides): Promise<void>;

    takeGameSessionBet(
      _bet: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "GameBalanceChanged(address,uint256)"(
      _game?: null,
      _amount?: null
    ): GameBalanceChangedEventFilter;
    GameBalanceChanged(
      _game?: null,
      _amount?: null
    ): GameBalanceChangedEventFilter;

    "GameFundsReceived(address,uint256)"(
      _game?: null,
      _amount?: null
    ): GameFundsReceivedEventFilter;
    GameFundsReceived(
      _game?: null,
      _amount?: null
    ): GameFundsReceivedEventFilter;

    "ProfitTaken(uint8,uint256,address)"(
      _type?: null,
      _amount?: null,
      _game?: null
    ): ProfitTakenEventFilter;
    ProfitTaken(
      _type?: null,
      _amount?: null,
      _game?: null
    ): ProfitTakenEventFilter;
  };

  estimateGas: {
    acceptPlay(
      _amount: BigNumberish,
      _profits: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    distributePlayWinnings(
      _winning: BigNumberish,
      _winner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getFunds(overrides?: CallOverrides): Promise<BigNumber>;

    getGameFunds(_game: string, overrides?: CallOverrides): Promise<BigNumber>;

    pay(
      _amount: BigNumberish,
      _sendTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    payGameSessionWinnings(
      _winning: BigNumberish,
      _profits: BigNumberish,
      _winner: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    receiveOraclePayment(
      _game: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    receiveRngPayment(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    takeGameSessionBet(
      _bet: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptPlay(
      _amount: BigNumberish,
      _profits: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    distributePlayWinnings(
      _winning: BigNumberish,
      _winner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getFunds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGameFunds(
      _game: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pay(
      _amount: BigNumberish,
      _sendTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    payGameSessionWinnings(
      _winning: BigNumberish,
      _profits: BigNumberish,
      _winner: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    receiveOraclePayment(
      _game: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    receiveRngPayment(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    takeGameSessionBet(
      _bet: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
