/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface GameInterface extends utils.Interface {
  contractName: "Game";
  functions: {};

  events: {
    "RngReceived(uint256)": EventFragment;
    "RngRequested(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RngReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RngRequested"): EventFragment;
}

export type RngReceivedEvent = TypedEvent<[BigNumber], { arg0: BigNumber }>;

export type RngReceivedEventFilter = TypedEventFilter<RngReceivedEvent>;

export type RngRequestedEvent = TypedEvent<[BigNumber], { arg0: BigNumber }>;

export type RngRequestedEventFilter = TypedEventFilter<RngRequestedEvent>;

export interface Game extends BaseContract {
  contractName: "Game";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GameInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "RngReceived(uint256)"(arg0?: null): RngReceivedEventFilter;
    RngReceived(arg0?: null): RngReceivedEventFilter;

    "RngRequested(uint256)"(arg0?: null): RngRequestedEventFilter;
    RngRequested(arg0?: null): RngRequestedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
